# fly.toml app configuration file for asd-backend

app = "asd-backend"
primary_region = "atl"

[build]
  # Uses Dockerfile in root directory to build the image

[http_service]
  internal_port = 5001
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1