export const periodicTableElements = {
    "1-1": { number: 1, symbol: "H", name: "Hydrogen", category: "nonmetal" },
    "1-18": { number: 2, symbol: "He", name: "Helium", category: "noble-gas" },
    "2-1": { number: 3, symbol: "Li", name: "Lithium", category: "alkali-metal" },
    "2-2": { number: 4, symbol: "Be", name: "Beryllium", category: "alkaline-earth" },
    "2-13": { number: 5, symbol: "B", name: "Boron", category: "metalloid" },
    "2-14": { number: 6, symbol: "C", name: "Carbon", category: "nonmetal" },
    "2-15": { number: 7, symbol: "N", name: "Nitrogen", category: "nonmetal" },
    "2-16": { number: 8, symbol: "O", name: "Oxygen", category: "nonmetal" },
    "2-17": { number: 9, symbol: "F", name: "Fluorine", category: "halogen" },
    "2-18": { number: 10, symbol: "Ne", name: "Neon", category: "noble-gas" },
    "3-1": { number: 11, symbol: "Na", name: "Sodium", category: "alkali-metal" },
    "3-2": { number: 12, symbol: "Mg", name: "Magnesium", category: "alkaline-earth" },
    "3-13": { number: 13, symbol: "Al", name: "Aluminium", category: "metalloid" },
    "3-14": { number: 14, symbol: "Si", name: "Silicon", category: "nonmetal" },
    "3-15": { number: 15, symbol: "P", name: "Phosphorus", category: "nonmetal" },
    "3-16": { number: 16, symbol: "S", name: "Sulphur", category: "nonmetal" },
    "3-17": { number: 17, symbol: "Cl", name: "Chlorine", category: "halogen" },
    "3-18": { number: 18, symbol: "Ar", name: "Argon", category: "noble-gas" },
    "4-1": { number: 19, symbol: "K", name: "Potassium", category: "alkali-metal" },
    "4-2": { number: 20, symbol: "Ca", name: "Calcium", category: "alkaline-earth" },
    "4-3": { number: 21, symbol: "Sc", name: "Scandium", category: "transition-metal" },
    "4-4": { number: 22, symbol: "Ti", name: "Titanium", category: "transition-metal" },
    "4-5": { number: 23, symbol: "V", name: "Vanadium", category: "transition-metal" },
    "4-6": { number: 24, symbol: "Cr", name: "Chromium", category: "transition-metal" },
    "4-7": { number: 25, symbol: "Mn", name: "Manganese", category: "transition-metal" },
    "4-8": { number: 26, symbol: "Fe", name: "Iron", category: "transition-metal" },
    "4-9": { number: 27, symbol: "Co", name: "Cobalt", category: "transition-metal" },
    "4-10": { number: 28, symbol: "Ni", name: "Nickel", category: "transition-metal" },
    "4-11": { number: 29, symbol: "Cu", name: "Copper", category: "transition-metal" },
    "4-12": { number: 30, symbol: "Zn", name: "Zinc", category: "transition-metal" },
    "4-13": { number: 31, symbol: "Ga", name: "Gallium", category: "post-transition" },
    "4-14": { number: 32, symbol: "Ge", name: "Germanium", category: "metalloid" },
    "4-15": { number: 33, symbol: "As", name: "Arsenic", category: "metalloid" },
    "4-16": { number: 34, symbol: "Se", name: "Selenium", category: "nonmetal" },
    "4-17": { number: 35, symbol: "Br", name: "Bromine", category: "halogen" },
    "4-18": { number: 36, symbol: "Kr", name: "Krypton", category: "noble-gas" },
    "5-1": { number: 37, symbol: "Rb", name: "Rubidium", category: "alkali-metal" },
    "5-2": { number: 38, symbol: "Sr", name: "Strontium", category: "alkaline-earth" },
    "5-3": { number: 39, symbol: "Y", name: "Yttrium", category: "transition-metal" },
    "5-4": { number: 40, symbol: "Zr", name: "Zirconium", category: "transition-metal" },
    "5-5": { number: 41, symbol: "Nb", name: "Niobium", category: "transition-metal" },
    "5-6": { number: 42, symbol: "Mo", name: "Molybdenum", category: "transition-metal" },
    "5-7": { number: 43, symbol: "Tc", name: "Technetium", category: "transition-metal" },
    "5-8": { number: 44, symbol: "Ru", name: "Ruthenium", category: "transition-metal" },
    "5-9": { number: 45, symbol: "Rh", name: "Rhodium", category: "transition-metal" },
    "5-10": { number: 46, symbol: "Pd", name: "Palladium", category: "transition-metal" },
    "5-11": { number: 47, symbol: "Ag", name: "Silver", category: "transition-metal" },
    "5-12": { number: 48, symbol: "Cd", name: "Cadmium", category: "transition-metal" },
    "5-13": { number: 49, symbol: "In", name: "Indium", category: "post-transition" },
    "5-14": { number: 50, symbol: "Sn", name: "Tin", category: "post-transition" },
    "5-15": { number: 51, symbol: "Sb", name: "Antimony", category: "metalloid" },
    "5-16": { number: 52, symbol: "Te", name: "Tellurium", category: "metalloid" },
    "5-17": { number: 53, symbol: "I", name: "Iodine", category: "halogen" },
    "5-18": { number: 54, symbol: "Xe", name: "Xenon", category: "noble-gas" },
    "6-1": { number: 55, symbol: "Cs", name: "Cesium", category: "alkali-metal" },
    "6-2": { number: 56, symbol: "Ba", name: "Barium", category: "alkaline-earth" },
    "6-3": { number: 57, symbol: "La", name: "Lanthanum", category: "lanthanoid" },
    "6-4": { number: 72, symbol: "Hf", name: "Hafnium", category: "transition-metal" },
    "6-5": { number: 73, symbol: "Ta", name: "Tantalum", category: "transition-metal" },
    "6-6": { number: 74, symbol: "W", name: "Tungsten", category: "transition-metal" },
    "6-7": { number: 75, symbol: "Re", name: "Rhenium", category: "transition-metal" },
    "6-8": { number: 76, symbol: "Os", name: "Osmium", category: "transition-metal" },
    "6-9": { number: 77, symbol: "Ir", name: "Iridium", category: "transition-metal" },
    "6-10": { number: 78, symbol: "Pt", name: "Platinum", category: "transition-metal" },
    "6-11": { number: 79, symbol: "Au", name: "Gold", category: "transition-metal" },
    "6-12": { number: 80, symbol: "Hg", name: "Mercury", category: "transition-metal" },
    "6-13": { number: 81, symbol: "Tl", name: "Thallium", category: "post-transition" },
    "6-14": { number: 82, symbol: "Pb", name: "Lead", category: "post-transition" },
    "6-15": { number: 83, symbol: "Bi", name: "Bismuth", category: "post-transition" },
    "6-16": { number: 84, symbol: "Po", name: "Polonium", category: "post-transition" },
    "6-17": { number: 85, symbol: "At", name: "Astatine", category: "halogen" },
    "6-18": { number: 86, symbol: "Rn", name: "Radon", category: "noble-gas" },
    "7-1": { number: 87, symbol: "Fr", name: "Francium", category: "alkali-metal" },
    "7-2": { number: 88, symbol: "Ra", name: "Radium", category: "alkaline-earth" },
    "7-3": { number: 89, symbol: "Ac", name: "Actinium", category: "actinoid" },
    "7-4": { number: 104, symbol: "Rf", name: "Rutherfordium", category: "transition-metal" },
    "7-5": { number: 105, symbol: "Db", name: "Dubnium", category: "transition-metal" },
    "7-6": { number: 106, symbol: "Sg", name: "Seaborgium", category: "transition-metal" },
    "7-7": { number: 107, symbol: "Bh", name: "Bohrium", category: "transition-metal" },
    "7-8": { number: 108, symbol: "Hs", name: "Hassium", category: "transition-metal" },
    "7-9": { number: 109, symbol: "Mt", name: "Meitnerium", category: "transition-metal" },
    "7-10": { number: 110, symbol: "Ds", name: "Darmstadtium", category: "transition-metal" },
    "7-11": { number: 111, symbol: "Rg", name: "Roentgenium", category: "transition-metal" },
    "7-12": { number: 112, symbol: "Cn", name: "Copernicium", category: "transition-metal" },
    "7-13": { number: 113, symbol: "Nh", name: "Nihonium", category: "post-transition" },
    "7-14": { number: 114, symbol: "Fl", name: "Flerovium", category: "post-transition" },
    "7-15": { number: 115, symbol: "Mc", name: "Moscovium", category: "post-transition" },
    "7-16": { number: 116, symbol: "Lv", name: "Livermorium", category: "post-transition" },
    "7-17": { number: 117, symbol: "Ts", name: "Tennessine", category: "halogen" },
    "7-18": { number: 118, symbol: "Og", name: "Oganesson", category: "noble-gas" },
    "8-4": { number: 58, symbol: "Ce", name: "Cerium", category: "lanthanoid" },
    "8-5": { number: 59, symbol: "Pr", name: "Praseodymium", category: "lanthanoid" },
    "8-6": { number: 60, symbol: "Nd", name: "Neodymium", category: "lanthanoid" },
    "8-7": { number: 61, symbol: "Pm", name: "Promethium", category: "lanthanoid" },
    "8-8": { number: 62, symbol: "Sm", name: "Samarium", category: "lanthanoid" },
    "8-9": { number: 63, symbol: "Eu", name: "Europium", category: "lanthanoid" },
    "8-10": { number: 64, symbol: "Gd", name: "Gadolinium", category: "lanthanoid" },
    "8-11": { number: 65, symbol: "Tb", name: "Terbium", category: "lanthanoid" },
    "8-12": { number: 66, symbol: "Dy", name: "Dysprosium", category: "lanthanoid" },
    "8-13": { number: 67, symbol: "Ho", name: "Holmium", category: "lanthanoid" },
    "8-14": { number: 68, symbol: "Er", name: "Erbium", category: "lanthanoid" },
    "8-15": { number: 69, symbol: "Tm", name: "Thulium", category: "lanthanoid" },
    "8-16": { number: 70, symbol: "Yb", name: "Ytterbium", category: "lanthanoid" },
    "8-17": { number: 71, symbol: "Lu", name: "Lutetium", category: "lanthanoid" },
    "9-4": { number: 90, symbol: "Th", name: "Thorium", category: "actinoid" },
    "9-5": { number: 91, symbol: "Pa", name: "Protactinium", category: "actinoid" },
    "9-6": { number: 92, symbol: "U", name: "Uranium", category: "actinoid" },
    "9-7": { number: 93, symbol: "Np", name: "Neptunium", category: "actinoid" },
    "9-8": { number: 94, symbol: "Pu", name: "Plutonium", category: "actinoid" },
    "9-9": { number: 95, symbol: "Am", name: "Americium", category: "actinoid" },
    "9-10": { number: 96, symbol: "Cm", name: "Curium", category: "actinoid" },
    "9-11": { number: 97, symbol: "Bk", name: "Berkelium", category: "actinoid" },
    "9-12": { number: 98, symbol: "Cf", name: "Californium", category: "actinoid" },
    "9-13": { number: 99, symbol: "Es", name: "Einsteinium", category: "actinoid" },
    "9-14": { number: 100, symbol: "Fm", name: "Fermium", category: "actinoid" },
    "9-15": { number: 101, symbol: "Md", name: "Mendelevium", category: "actinoid" },
    "9-16": { number: 102, symbol: "No", name: "Nobelium", category: "actinoid" },
    "9-17": { number: 103, symbol: "Lr", name: "Lawrencium", category: "actinoid" }
}

export const categories = {
  "alkali-metal": "#ff6666",
  "alkaline-earth": "#ffdead",
  "transition-metal": "#ffc0c0",
  "post-transition": "#cccccc",
  "metalloid": "#cccc99",
  "nonmetal": "#a1ffc3",
  "halogen": "#ffff99",
  "noble-gas": "#c0ffff",
  "lanthanoid": "#ffbfff",
  "actinoid": "#ff99cc"
};